version: '2'
 
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    networks:
      - local
volumes:
  rabbitmq_data:
    driver: local
networks:
  local:
    external: true
