version: '3'

services:
  order-app:
    container_name: "order-app"
    image: 'golang:1.9-stretch'
    volumes:
      - '.:/go'
    ports:
      - '3003:3003'
      - '9003:9003'
    command: 'go run main.go'
    links:
      - order-mysql
    external_links:
      - user-app
      - rabbitmq
    networks:
      - local
  order-mysql:
    container_name: "order-db"
    image: mysql
    ports:
      - "3310:3306"
    environment:
      # MYSQL_DATABASE: sample 初期ファイルで実行するのでdockerでは作成しない
      MYSQL_CHARSET: utf8
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      TZ: "Asia/Tokyo"
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - mysql:/var/lib/mysql
    networks:
      - local

volumes:
  mysql:
    driver: 'local'

networks:
  local:
    external: true